### ISSUE TITLE
SocketException ('Access denied' or 'Invalid argument') at 'EndSendTo' method of 'RTPChannel' when we use UDP in iOS

### ISSUE THREAD

**Issue by neminush** [sipsorcery-org/sipsorcery#336]
Look at 'RTPChannel.cs' --> 'private void EndSendTo(IAsyncResult ar)' --> 'catch (SocketException sockExcp)'.

I create a 'SIPTransport' like that:
`_transport = new SIPTransport();`
`_transport.AddSIPChannel(new SIPUDPChannel(new IPEndPoint(IPAddress.Any, 5060)));`

Next, I create a session like that:
`MediaEndPoints mediaEndPoints = _mediaEndPointsFactory.Create();`
`var mediaSession = new VoIPMediaSession(mediaEndPoints, bindAddress: null, 18200);`
`bool isAnswered = await _userAgent.Answer(_serverUserAgent, mediaSession);`

On Android devices and Android emulators code works fine.

But on iPhone (real device) in 'EndSendTo' method I always get this:
`{System.Net.Sockets.SocketException (0x80004005): Access denied`
`  at System.Net.Sockets.SocketAsyncResult.CheckIfThrowDelayedException () [0x0003b] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/SocketAsyncResult.cs:134`
`  at System.Net.Sockets.Socket.EndSendTo (System.IAsyncResult asyncResult) [0x0002c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/Current/src/Xamarin.iOS/mcs/class/System/System.Net.Sockets/Socket.cs:2393`
`  at SIPSorcery.Net.RTPChannel.EndSendTo (System.IAsyncResult ar) [0x0000e] in ......./SIPSorcery/net/RTP/RTPChannel.cs:428 }`
`	base: {System.ComponentModel.Win32Exception}`
`	ErrorCode: 10013`
`	Message: "Access denied"`
`	SocketErrorCode: System.Net.Sockets.SocketError.AccessDenied`

But if run the same code in iPhone simulator I always get a 'SocketException' with '10022' error code and 'Invalid arguments' message.

I need help :'(

**Comment by neminush** [comment]
The problem is solved if you explicitly specify the 'bindAddress' parameter for 'VoIPMediaSession'.

But there is another problem here: how to find out the ip address.

**Comment by neminush** [comment]
As far as I understand these problems we have because of this:
https://github.com/mono/mono/issues/20339

@sipsorcery, you mentioned it here:
https://github.com/sipsorcery/sipsorcery/issues/302#issuecomment-708039892

Now I'm looking for a way out of this situation...

**Comment by sipsorcery** [comment]
I'm attempting to replicate this issue.

The [WebRTC XamarinDataChannelTest demo](https://github.com/sipsorcery/sipsorcery/tree/master/examples/WebRTCExamples/XamarinDataChannelTest) did previously work on my iPhone. The WebRTC logic uses the same `RTPChannel` class as the SIP logic. I still have the app on my iPhone but it's not connecting now so looks like somethings changed.

**Comment by sipsorcery** [comment]
I was able to reproduce the error in the iOS emulator.

I attempted to a basic SIP call using `mono` runtime on WIndows 10 and encountered yet a different socket error.

`[16:17:35 WRN] SocketException RTPChannel EndSendTo (10014). The system detected an invalid pointer address in attempting to use a pointer argument in a call.`

**Comment by sipsorcery** [comment]
> But there is another problem here: how to find out the ip address in iOS.

Using the default address worked for me in the emulator.

`var res = await _userAgent.Call(DESTINATION, null, null, new AudioSendOnlyMediaSession(SIPSorcery.Sys.NetServices.InternetDefaultAddress));`

var res = await _userAgent.Call(DESTINATION, null, null, new AudioSendOnlyMediaSession(NetServices.InternetDefaultAddress));

**Comment by neminush** [comment]
Now, I got out of this problem situation by getting an ip address using this code below.  This works on both iPhone and Android devices.


    public static class NetworkHelper
    {
        public static IPAddress GetLocalIPAddress()
        {
            NetworkInterface[] networkInterfaces = NetworkInterface.GetAllNetworkInterfaces();

            if (networkInterfaces.IsNullOrEmpty())
                return null;

            foreach (NetworkInterface networkInterface in networkInterfaces)
            {
                if (networkInterface.NetworkInterfaceType == NetworkInterfaceType.Wireless80211 ||
                    networkInterface.NetworkInterfaceType == NetworkInterfaceType.Ethernet)
                {
                    UnicastIPAddressInformationCollection unicastIpCollection = networkInterface.GetIPProperties().UnicastAddresses;

                    if (unicastIpCollection is null)
                        continue;

                    foreach (UnicastIPAddressInformation ipInformation in unicastIpCollection)
                    {
                        if (ipInformation.Address?.AddressFamily == AddressFamily.InterNetwork)
                        {
                            return ipInformation.Address;
                        }
                    }
                }
            }

            return null;
        }
    }

**Comment by neminush** [comment]
The solution with the "SIPSorcery.Sys.NetServices.InternetDefaultAddress" I will check next week on Monday. I will write the test result here.

**Comment by rafcsoares** [comment]
@sipsorcery seems that this issue contains relation with #340 

I fixed the EndSendTo Exception changing RTPChannel.cs Send function

```
//Prevent Send to IPV4 while socket is IPV6 (Mono Error)
 if(dstEndPoint.AddressFamily == AddressFamily.InterNetwork && sendSocket.AddressFamily != dstEndPoint.AddressFamily)
              dstEndPoint = new IPEndPoint(dstEndPoint.Address.MapToIPv6(), dstEndPoint.Port);

sendSocket.BeginSendTo(buffer, 0, buffer.Length, SocketFlags.None, dstEndPoint, EndSendTo, sendSocket);
return SocketError.Success;
```

**Comment by neminush** [comment]
I have checked. An app works on mobile devices with 'SIPSorcery.Sys.NetServices.InternetDefaultAddress', but the ip address changes frequently on smartphones.
![InternetDefaultAddress](https://user-images.githubusercontent.com/33318899/97984871-6d66bd80-1de8-11eb-9f0e-d3230582ffe6.png)

**Comment by neminush** [comment]
I have also checked the rafcsoares's solution. It works good with 'bindAddress' set to 'IPAddress.Any' in iOS devices and in Android devices.

![workaround - mono error](https://user-images.githubusercontent.com/33318899/97985174-f2ea6d80-1de8-11eb-9bf9-7e476258730d.png)
